export const EUDR_CUTOFF_DATE = '2020-12-31';
export const EUDR_VALIDITY_MONTHS = 6;

export const EUDR_VALIDATION_HISTORY_DEFAULT_PAGE = 1;
export const EUDR_VALIDATION_HISTORY_DEFAULT_LIMIT = 10;
export const EUDR_VALIDATION_HISTORY_MAX_LIMIT = 100;
